# Generated by Django 2.0.1 on 2018-03-27 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180327_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_phone_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{1,12}$', 'Only Numbers and Upper are allowed (max. 6)')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_phone_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{1,12}$', 'Only Numbers and Upper are allowed (max. 6)')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='quarter_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residence_number',
            field=models.CharField(max_length=10),
        ),
    ]
